{
 "title": "InfluxDB-Stats-Internal",
 "description": "InfluxDB internal performance",
 "tags": [
  "Influxdb",
  "Metric",
  "Internal"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "InfluxDB-Hostname",
    "query": "SHOW TAG VALUES FROM \"database\" WITH KEY = \"hostname\""
   }
  ]
 },
 "panels": [
  { "title": "InfluxDB-Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Influxdb Overview --> $hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "InfluxDB Active Queries",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "queryExecutor",
     "select": [
      [
       { "params": [ "queriesActive" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "InfluxDB Executed Queries",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "queryExecutor",
     "select": [
      [
       { "params": [ "queriesExecuted" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "InfluxDB Finished Queries",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "queryExecutor",
     "select": [
      [
       { "params": [ "queriesFinished" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "InfluxDB Recovered/Panic Queries",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "queryExecutor",
     "select": [
      [
       { "params": [ "recoveredPanics" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "description": "queryOk\nThe total number of continuous queries that executed successfully. Note that this value may be incremented in some cases where a CQ is initiated but does not actually run, for example, due to misconfigured resample intervals.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
   "targets": [
    {
     "alias": "$col per 1 minute",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cq",
     "select": [
      [
       { "params": [ "queryOk" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Continues OK Query" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "description": "queryFail\nThe total number of continuous queries that executed but failed.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "targets": [
    {
     "alias": "$col per 1 minute",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cq",
     "select": [
      [
       { "params": [ "queryFail" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Continues Failed Query" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Influxdb Query Duration per 1minute interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queryExecutor",
     "select": [
      [
       { "params": [ "queryDurationNs" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Query Duration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage per Database shard",
   "type": "bargauge",
   "description": "Single shard per database name",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "alias": "Database: $tag_database",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "shard",
     "select": [
      [
       { "params": [ "diskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Database Write Errors ",
   "type": "singlestat",
   "description": "writeError\nThe total number of batches of points that were not successfully written, due to a failure to write to a local or remote shard.\n\nThe write measurement statistics are about writes to the data node, regardless of the source of the write.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "write",
     "select": [
      [
       { "params": [ "writeError" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Write Errors" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Database Write Timeouts / per 1 min",
   "type": "singlestat",
   "description": "writeTimeout\nThe total number of write requests that failed to complete within the default write timeout duration. This could indicate severely reduced or contentious disk I/O or a congested network to a remote node. For a single write request that comes in over HTTP or another input method, writeTimeout will be incremented by 1 if the entire batch is not written within the timeout period, regardless of whether the points within the batch can be written locally or remotely.\n\nThe write measurement statistics are about writes to the data node, regardless of the source of the write.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "write",
     "select": [
      [
       { "params": [ "writeTimeout" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Write Timeouts" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Httpd Stats --> $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Http Requests ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col / per 1min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "select": [
      [
       { "params": [ "writeReq" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Write Request " ], "type": "alias" }
      ],
      [
       { "params": [ "queryReq" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Query Requests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Http Client/Server errors",
   "type": "graph",
   "description": "clientError\nThe number of HTTP responses due to client errors, with a 4XX HTTP status code.\n\nserverError\nThe number of HTTP responses due to server errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col / per 1min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "select": [
      [
       { "params": [ "serverError" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Server Errors" ], "type": "alias" }
      ],
      [
       { "params": [ "clientError" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Client Errors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Runtime/Memory --> $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "InfluxDB Runtime Heap allocation stats",
   "type": "graph",
   "description": "HeapInUse\nThe number of bytes in in-use spans.\n\nHeapIdle\nThe number of bytes of idle heap objects.\n\nHeapReleased\nThe number of bytes of physical memory returned to the OS.\n\nThe runtime measurement statistics include a subset of MemStats records statistics about the Go memory allocator. The runtime statistics can be useful to determine poor memory allocation strategies and related performance issues.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "HeapInUse" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Heap in Use" ], "type": "alias" }
      ],
      [
       { "params": [ "HeapIdle" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Heap idle" ], "type": "alias" }
      ],
      [
       { "params": [ "HeapReleased" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Heap Released" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "InfluxDB Runtime Allocs and Frees ",
   "type": "graph",
   "description": "Alloc\nThe currently allocated number of bytes of heap objects.\n\nFrees\nThe cumulative number of freed (live) heap objects.\n\nThe runtime measurement statistics include a subset of MemStats records statistics about the Go memory allocator",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "Alloc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Alloc" ], "type": "alias" }
      ],
      [
       { "params": [ "Frees" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Frees" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Measurements/Series--> $hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "Databases Measurement Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col  $tag_database database",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "database",
     "select": [
      [
       { "params": [ "numMeasurements" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Measurements --" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Databases Series Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col  $tag_database database",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "database",
     "select": [
      [
       { "params": [ "numSeries" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Series --" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}