{
 "title": "Linux-Hosts-stats",
 "tags": [
  "linux",
  "system",
  "performance"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "linux_hostname",
    "label": "Linux-Hostname",
    "query": "SHOW TAG VALUES FROM system WITH Key=host"
   },
   {
    "name": "interface",
    "label": "interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$linux_hostname/"
   },
   {
    "name": "disk",
    "label": "disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH Key = \"name\"  "
   }
  ]
 },
 "panels": [
  {
   "title": "Linux Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "Overview --> $linux_hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Shows Max Value",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " *-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "IOWAIT",
   "type": "singlestat",
   "description": "CPU waiting for DiskIO ",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "/ Root Usage",
   "type": "bargauge",
   "description": "Root File system usage percentage",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "/ Root Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 2 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total Size" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "bargauge",
   "description": "Swap Partition Percentage usage",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
     ]
    }
   ]
  },
  { "title": "CPU --> $linux_hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU usage % stats",
   "type": "graph",
   "description": "VM Stolen Time - Percentage of CPU time that was stolen from a virtual machine",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "User Space" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "System/Kernel" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "IOwait" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "VM Stolen time" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_irq" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "irq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "softirq" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage % per CPU_ID ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " *-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Running Processes" ], "type": "alias" }
      ],
      [
       { "params": [ "sleeping" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Sleeping Processes" ], "type": "alias" }
      ],
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Blocked Processes" ], "type": "alias" }
      ],
      [
       { "params": [ "zombies" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Zombie Processes" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total Processes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory --> $linux_hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage Breakdown",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Total Memory" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Used Memory" ], "type": "alias" }
        ],
        [
         { "params": [ "cached" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Cached Memory" ], "type": "alias" }
        ],
        [
         { "params": [ "buffered" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Buffered Memory" ], "type": "alias" }
        ],
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Free Memory" ], "type": "alias" }
        ],
        [
         { "params": [ "mapped" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Mapped Memory" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Swap Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "swap_total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Swap Total Memory" ], "type": "alias" }
        ],
        [
         { "params": [ "swap_free" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Swap Free Memory" ], "type": "alias" }
        ],
        [
         { "params": [ "swap_cached" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Swap Cached Memory" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Total Memory" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Used Memory" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "System --> $linux_hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load",
     "type": "graph",
     "description": "System load can exeed ",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Average Load per 1 minute" ], "type": "alias" }
        ],
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Average Load per 5 minute" ], "type": "alias" }
        ],
        [
         { "params": [ "load15" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Average Load per 15 minute" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network --> $linux_hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(max(\"bytes_recv\"), 10s) FROM \"net\" WHERE (\"host\" =~ /^$linux_hostname$/ AND \"interface\" =~ /^$interface$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ " *8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      },
      {
       "alias": "$tag_interface - TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(max(\"bytes_sent\"), 10s)  *8 FROM \"net\" WHERE (\"host\" =~ /^$linux_hostname$/) AND $timeFilter GROUP BY time($__interval), \"interface\" fill(null)",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ " *8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - packets RX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(max(\"bytes_recv\"), 10s) FROM \"net\" WHERE (\"host\" =~ /^$linux_hostname$/ AND \"interface\" =~ /^$interface$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "packets_recv" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      },
      {
       "alias": "$tag_interface - packets TX",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(max(\"bytes_recv\"), 10s) FROM \"net\" WHERE (\"host\" =~ /^$linux_hostname$/ AND \"interface\" =~ /^$interface$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "packets_sent" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Packet Drops ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - drops_in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(max(\"drop_in\"), 10s) FROM \"net\" WHERE (\"host\" =~ /^$linux_hostname$/ AND \"interface\" =~ /^$interface$/) AND $timeFilter GROUP BY time($__interval), \"interface\" fill(null)",
       "select": [
        [
         { "params": [ "drop_in" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      },
      {
       "alias": "$tag_interface - drops_out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(max(\"bytes_recv\"), 10s) FROM \"net\" WHERE (\"host\" =~ /^$linux_hostname$/ AND \"interface\" =~ /^$interface$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "drop_out" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Packet Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - error_in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(max(\"bytes_recv\"), 10s) FROM \"net\" WHERE (\"host\" =~ /^$linux_hostname$/ AND \"interface\" =~ /^$interface$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "err_in" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      },
      {
       "alias": "$tag_interface - error_out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(max(\"bytes_recv\"), 10s) FROM \"net\" WHERE (\"host\" =~ /^$linux_hostname$/ AND \"interface\" =~ /^$interface$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "err_out" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "The number of entries in the conntrack table",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "conntrack",
       "select": [
        [
         { "params": [ "ip_conntrack_count" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "ip_countract_count" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "The max capacity of the conntrack table",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "conntrack",
       "select": [
        [
         { "params": [ "ip_conntrack_max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [
           "The max capacity of the conntrack table"
          ],
          "type": "alias"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Ethtool RX / TX Queue per Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_interface -- $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ethtool",
       "select": [
        [
         { "params": [ "Rx Queue#" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Queue RX" ], "type": "alias" }
        ],
        [
         { "params": [ "Tx Queue#" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Queue TX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk --> $linux_hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Path Size / Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "alias": "$tag_path --> $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "total" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "swap",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "swap --> total" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "swap --> used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk Path % used",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "alias": "$tag_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "swap",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "swap" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Inodes Status per Path",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_path --> $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "inodes_total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Inodes - total" ], "type": "alias" }
        ],
        [
         { "params": [ "inodes_used" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Inodes - used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_name | $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "reads" ], "type": "alias" }
        ],
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "writes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O reads/writes ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_name | $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "reads" ], "type": "alias" }
        ],
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "writes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O time ",
     "type": "graph",
     "description": "read_time & write_time:\nThese values count the number of milliseconds that I/O requests have waited on this block device. If there are multiple I/O requests waiting, these values will increase at a rate greater than 1000/second; for example, if 60 read requests wait for an average of 30 ms, the read_time field will increase by 60*30 = 1800.\n\nio_time:\nThis value counts the number of milliseconds during which the device has had I/O requests queued.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_name | $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "read_time" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "reads" ], "type": "alias" }
        ],
        [
         { "params": [ "write_time" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "writes" ], "type": "alias" }
        ],
        [
         { "params": [ "io_time" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "io queue" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "SWAP I/O bytes",
     "type": "graph",
     "description": "in (int, bytes): data swapped in since last boot calculated from page number\nout (int, bytes): data swapped out since last boot calculated from page number",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "swap",
       "select": [
        [
         { "params": [ "in" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [
           "data swapped in since last boot | in"
          ],
          "type": "alias"
         }
        ],
        [
         { "params": [ "out" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [
           "data swapped out since last boot | out"
          ],
          "type": "alias"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Kernel --> $linux_hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interrupts",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "select": [
        [
         { "params": [ "interrupts" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "Interrupts" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "select": [
        [
         { "params": [ "context_switches" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "Context Switches" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Processes Forked",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "select": [
        [
         { "params": [ "processes_forked" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "Process Forked" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$linux_hostname$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}